# Generated by Django 5.0.6 on 2024-06-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_media_rename_emprunteur_member_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
    ]
