# Generated by Django 5.0.6 on 2024-06-05 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cd_date_emprunt_remove_cd_emprunteur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='date_emprunt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dvd',
            name='date_emprunt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dvds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre',
            name='date_emprunt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to=settings.AUTH_USER_MODEL),
        ),
    ]
